version: '3'
services:

  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban

  kanban-app:
    image: ghcr.io/nikhiljiddigi/kanban-app:latest
    container_name: kanban-app
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8888:8080
    links:
      - kanban-postgres

  kanban-ui:
    image: ghcr.io/nikhiljiddigi/kanban-ui:latest
    container_name: kanban-ui
    ports:
      - 80:80
    links:
      - kanban-app


volumes:
  kanban-data:
