apiVersion: v2
name: kanban-product
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: kanban-ui
    version: 0.1.0
    condition: kanban-ui.enabled
    repository: file://../helm-charts/kanban-ui
  - name: kanban-app
    version: 0.1.0
    condition: kanban-app.enabled
    repository: file://../helm-charts/kanban-app
  - name: postgres
    version: 0.1.0
    condition: kanban-postgres.enabled
    repository: file://../helm-charts/postgres
version: 0.0.1
appVersion: 0.0.1-1.0.0
